### ISSUE TITLE
Contract created before instantiated

### ISSUE THREAD

**Issue by Buckram123** [CosmWasm/cw-multi-test#226]
On chains contract does not exist until instantiation have finished. It means that querying `contract_info` on `env.contract.address` during instantiation would fail with `No such contract: ADDRESS: instantiate wasm contract failed`. 
The issue is that `cw-multi-test` does not error in this case. Would be nice to replicate chain behavior!

**Comment by chipshort** [comment]
I wonder if we should consider this a bug on the wasmd side. If we do, we should probably align the two behaviors by adjusting the behavior on the chain side. Any opinions on this?

**Comment by Buckram123** [comment]
> I wonder if we should consider this a bug on the wasmd side. If we do, we should probably align the two behaviors by adjusting the behavior on the chain side. Any opinions on this?

I would expect contract to know code id it's instantiated with. Agree that it's wasmd bug

**Comment by chipshort** [comment]
Alright, I've created a wasmd issue for this now: https://github.com/CosmWasm/wasmd/issues/2044
Do I understand correctly that the current MultiTest behavior is to return the same ContractInfo you would get after instantiation? Because in that case, I think we can close here and continue in the wasmd issue.
