### ISSUE TITLE
Allow mocking Stargate messages

### ISSUE THREAD

**Issue by 0xphilipp** [CosmWasm/cw-multi-test#40]
It would be great to be able to mock stargate messages.

https://github.com/CosmWasm/cw-multi-test/blob/42d8e9bb192362e9ee89074a5efd5d3ff52e91c4/src/app.rs#L943

It is not about supporting stargate messages, but only being able to accept them and update some state for testing.

**Comment by epanchee** [comment]
I also agree with the said above.

It would be great to include this as a failing module in the default App, allowing devs to replace it with a custom Stargate module in AppBuilder. This feature could significantly simplify the testing of multi-stage contract executions.

While some CosmWasm-enabled chains are transitioning their testing to test-tube, it's important to note that it doesn't provide a comprehensive coverage report. For sophisticated DeFi projects with substantial value at stake, having only 10% or even zero test coverage is a concerning issue in the crypto space, in my opinion. That's why I appreciate the functionality of cw-multitest and would like to request your support in incorporating it.

Is it possible to prioritize this request? I believe it shouldn't be too challenging to implement, in my opinion.

**Comment by DariuszDepta** [comment]
Hi @0xphilipp, could you check if PR #106 addresses your needs, or we are missing something? Thanks in advance for your help!
