### ISSUE TITLE
Remove `ProcessQueue` made-up sudo message for staking processing

### ISSUE THREAD

**Issue by maurolacy** [CosmWasm/cw-multi-test#53]
The staking module has a made-up `ProcessQueue` sudo message to process the pending staking / unstakings.

This could be easily modified / improved, to call the `ProcessQueue` message handler under the hood before each query.

This can be done during / before every balance query. A little overkill, but since the queue is almost always empty.
It can also be done on `update_block`, after block updating.
Perhaps in both places for robustness, as the second call (empty queue) will be really cheap.

**Comment by chipshort** [comment]
Getting rid of that message would be really nice for usability.
One thing to note here is that this processing needs mutable storage access. In order to do it in a query, we have to create a separate function that does not update storage and just returns the differences (and those can then be used e.g. in the balance query to adjust the balances).
So, doing this only in `update_block` and `set_block` might be easier (and I think also more realistic, since in the sdk, it happens in the end blocker?).
